### PR TITLE
Feature/recommended services

### PR DESCRIPTION
**Pull request by appsol**
### Summary
https://trello.com/c/kBP9HlxC

- Add drop down to allow Super Admin to set a score for a service
- Show the service score only to Super Admin

### Development checklist
- [x] The code has been linted `npm run lint --fix`

### Release checklist
NA

### Notes
NA

### CODE REVIEW

**Review by matthew-inamdar — APPROVED** [review]
LGTM - tested and works great.

**Comment by matthew-inamdar** [comment]
@appsol small conflict to resolve

**Comment by appsol** [comment]
@matthew-inamdar Resolved conflict

**Review by matthew-inamdar — APPROVED** [review]
LGTM 👍

**Pull request merged**
