### PR TITLE
Feature/organisation duplicate management

### PR DESCRIPTION
**Pull request by appsol**
### Summary
https://trello.com/c/Dd3mNnqp

- Duplicates returned in api response are shown within the error table
- Each row can show 1 or more duplicate organisations
- Duplicates are shown as the Organisation name linked to it's page in admin
- Each duplicate has an 'Ignore' toggle switch, this will pass the ID of the duplicate back to the API allowing the clash to be ignored, i.e. the new organisation will be added with a different slug.
- Once rows to ignore are selected, the file must be re-uploaded.
- Insert is atomic, even if some rows are ignored, if any duplicates remain the whole insert will fail and all duplicates returned

### Development checklist
- [x] The code has been linted `npm run lint --fix`

### Release checklist
NA

### Notes
NA

### CODE REVIEW

**Comment by matthew-inamdar** [comment]
@appsol please resolve the conflicts from `develop`, as the service bulk import has now been merged in.

**Comment by appsol** [comment]
@matthew-inamdar Resolved conflicts.

**Review by matthew-inamdar — CHANGES_REQUESTED** [review]
Looks really good 👍 

I've noticed that the file is removed from the input when there are duplicates. Could you take a look and see if there's anything we can do to prevent that? I'm not sure if this is just strange behaviour from Chrome?

**Comment by appsol** [comment]
@matthew-inamdar So this is actually behaviour that I put in place, let me explain.
1. User browses for file
2. User uploads file
3. Errors are returned (either duplicate or other)
4. To resolve the errors user will need to edit the spreadsheet and re-upload

If I leave the filename in place it can confuse the user at point 4 as they may try to re-upload the same file. This will not work anyway as the file is base64 encoded prior to upload and the name of the file is displayed by the button, but it is not the binary file that is uploaded, it is the base64 data created from the file.
By clearing the file name, this prompts the user to re-attach a file (hopefully following editing or they will get the same errors), which then gets read in as fresh base64 data.
Does this make sense?

**Comment by matthew-inamdar** [comment]
@appsol If the user wants to ignore the duplicates and upload the spreadsheet without editing it, does this mean they'll need to reattach it?

**Comment by appsol** [comment]
@matthew-inamdar Yes it does, but that is better than letting them re-upload the spreadsheet without any amends they may have made. I have altered the spreadsheet error response so if it is a duplicate within the spreadsheet a simple warning is issued as they cannot add this row to the ignore duplicates array.

**Review by matthew-inamdar — APPROVED** [review]

**Pull request merged**
